name: Publish Brain

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          cache: npm
      - run: npm ci
      - run: npm run build-brain
      - name: copy file with ssh password
        uses: appleboy/scp-action@v0.1.7
        with:
          host: joshy.org
          username: deployman
          port: 22
          key: ${{secrets.DEPLOYMAN_PRIVATE_KEY}}
          source: "temp/*.html"
          target: /home/joshy/sites/apps.josh.earth/brain
          strip_components: 1

